<?php

namespace Sinarahmany\LaravelVoipMs;

use Illuminate\Support\ServiceProvider;

class VoipMsServiceProvider extends ServiceProvider
{
    public function boot(): void
    {

        $this->mergeConfigFrom(
            __DIR__.'/config/voipms.php', 'voipms'
        );

        $this->publishes([
            __DIR__.'/config/voipms.php' => config_path('voipms.php'),
        ]);
    }

    public function register():void
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind('voipms', function($app) {
            return new VoipMs();
        });

    }
}
